# Generated by Django 5.2.12 on 2026-03-09 00:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("rating", models.IntegerField(default=1200)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("draws", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-rating", "-wins"],
            },
        ),
        migrations.AlterModelOptions(
            name="matchrecord",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="matchrecord",
            name="game_state",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="matchrecord",
            name="mode",
            field=models.CharField(default="local", max_length=20),
        ),
        migrations.AddField(
            model_name="matchrecord",
            name="room_code",
            field=models.CharField(
                db_index=True, default=core.models.default_room_code, max_length=16
            ),
        ),
        migrations.AddField(
            model_name="matchrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
